#!/bin/bash
#set -x
clear

INC="$(pwd)/inc"
DIR_LANG="$(pwd)/lang" #&& echo $DIR_LANG
lang="${LANG:0:2}" #&& echo $LANG
# link texts and titles variables
[[ -f "${DIR_LANG}/titles.${lang}" ]] && source "${DIR_LANG}/titles.${lang}" || source "${DIR_LANG}/titles.en"
[[ -f "${DIR_LANG}/texts.${lang}" ]] && source "${DIR_LANG}/texts.${lang}" ||source "${DIR_LANG}/texts.en"

# link files needed
source "${INC}/config"
source "${INC}/colors"

# link functions needed
source "${INC}/zenity"
source "${INC}/display"
source "${INC}/RK_functions"
source "${INC}/functions"

# genesis
echo "${title_welcome}"

# test
test_config_file
verify_installed

# menu
display_menu

# destruct
destruct_vars
