#!/bin/bash

function display_detected() {

    echo -e "${green}$1${neutral}"

    write_file "log" "### Detected: $1"

}

function display_error() {

    if [[ "${ZENITY}" -ne 0 ]]; then
        zenity_error "<span color=\"red\">$1</span>" "$2"
    else
        echo -e "${red}$1${neutral}"
    fi

    write_file "log" "### Error: $1"

}

function display_files_to_flash() {

    if [[ "${ZENITY}" -ne 0 ]]; then

        files=$( echos_files_to_save | zenity_list_files "${text_menu_files}" "${title_menu_files}" "${#mtd_name[@]}")

    else

        dialog_list_files "${text_menu_files}" "${title_menu_files}" "${#mtd_name[@]}"
        [[ $? -eq 0 ]] && files=$(<"${FILE_TMP}")

    fi

    [[ "$files" ]] && write_file "log" "### Files choosed: ${files}"

}

function display_menu() {

    while true; do
        choice=""

        if [[ "${ZENITY}" -ne 0 ]]; then
            choice=$( echos_menu | zenity_list "${text_welcome}" "${title_welcome}" "${count['name']}")

        elif  [[ "${DIALOG}" -ne 0 ]]; then
            echos_menu
            dialog_menu "${text_welcome}" "${title_welcome}" "${count['name']}"

            [[ $? -eq 0 ]] && choice=$(<"${FILE_TMP}")
            rm "${FILE_TMP}.menu"
        else
            echo "${title_welcome}"

            PS3="${text_welcome} ${text_quit} "
            select menu in "${text_menu_description[@]}"
            do
                if [[ "$REPLY" == "q" || "$REPLY" == "Q" ]]; then
                    choice="${text_menu_name[${#text_menu_name[*]}]}"
                else
                    choice="${text_menu_name[$REPLY]}"
                fi
                break
            done

        fi

        unset menu

        # if choice exists, then run-it!
        #[[ "$choice" ]] && "$choice"
        if [[ "$choice" ]]; then
            #array=("${text_menu_name[@]}")
            #key=$(get_key "${choice}");
            local key="$(array_search ${choice} ${text_menu_name[@]})"

            [[ -z "$key" ]] && unset choice || "$choice";
            unset array key
        fi

    done

    [[ $? -ne 0 ]] && EXIT

}

function display_mssg() {

    if [[ "${ZENITY}" -ne 0 ]]; then

        case "$1" in
            i) zenity_info "$2" "$3" ;;
            n) zenity_notify "$2" "$3" ;;
            q) zenity_question "$2" "$3" ;;
        esac

    else

        case "$1" in
            q) read -p "$(echo -e $2 ${text_yes_no} )" answer ;;
            *) echo -e "$2" ;;
        esac

    fi

    write_file "log" "### Message: $2"

}

function display_mtd() {

    for (( i=0 ; i < ${#mtd[@]} ; i++ )); do
        echo -e "${vertclair}\tFound partition '${mtd_name[$i]}' of size '${mtd_size[$i]}' at offset '${mtd_offset[$i]}'${neutre}\n";
    done

}

function echos_files_to_save() {

    array=("${FILES[@]}")
    y=0

    for (( x=0 ; x < ${#mtd_name[@]} ; x++ )); do

        #key=$(get_key "${mtd_name[$x]}")
        local key="$(array_search ${mtd_name[$x]} ${mtd_name[@]})"

        if [[ $DIALOG -eq 1 ]]; then
            [[ -n "$key" ]] &&  key=" on" || key=" off"
            let "y = $x + 1"
            list="${mtd_name[$x]} offset:${mtd_offset[$x]} $key"
            echo "$list"
        fi

        if [[ $ZENITY -eq 1 ]]; then
            [[ -n "$key" ]] && echo TRUE || echo FALSE
            echo "${mtd_name[$x]}"
            echo "${mtd_offset[$x]}"
        fi

    done

    unset array

}

function echos_menu() {

    i=1

    if [[ $DIALOG -eq 1 ]]; then

        while [ $i -le ${#text_menu_name[@]} ]; do
            echo "${text_menu_name[$i]}|${text_menu_description[$i]}" >> "${FILE_TMP}.menu"
            let "i = $i + 1";
        done

        OFS="$IFS"
        while IFS="|" read col1 col2 || [ -n "$col1" ]; do
            menu+=("$col1" "$col2")
        done < "${FILE_TMP}.menu"
        IFS="$OFS"

    else
        while [ $i -le ${#text_menu_name[@]} ]; do
            echo "${text_menu_name[$i]}";
            echo "${text_menu_description[$i]}";
            let "i = $i + 1";
        done
    fi

	unset i;

}
