#!/bin/bash

function adb_to_bootloader() {

    display_mssg "i" "${text_adb_reboot_bootloader}" "${title_adb_reboot_bootloader}"
    ${adb} reboot-bootloader

}

function erase_idb() {

    ${rkflash} e 0x00 0x2000

}

function reboot_tablet() {

    display_mssg "n" "${text_reboot}" "${title_reboot}"

    ${rkflash} b

}

function rkflash_read_parameter()  {

    write_file "log" "*** rkflashtool: read file parameter named $1"

    ${rkflash} p > "$1"

}

function rkflash_read_rom() {

    write_file "log" "*** rkflashtool: read rom from tablet "
    #p='bc <<< ${count["files"]}/100'

    if [[ -d "${DIR_SVG_DATED}" ]]; then
        for (( x=0 ; x < ${count["files"]} ; x++ )); do

            [[ "${FILES[$x]}" == "${FILES[4]}" ]] && x=8
            $(${rkflash} r ${mtd_offset[$x]} ${mtd_size[$x]} > ${DIR_SVG_DATED}/${mtd_name[$x]}.img)
            write_file "log" "${rkflash} r ${mtd_offset[$x]} ${mtd_size[$x]} > ${DIR_SVG_DATED}/${mtd_name[$x]}.img"
            display_mssg "n" "Saved ${mtd_name[$x]}.img into ${DIR_SVG_DATED}"
            #echo "$p"
            #$(p+=$p)
            #let "p = $p + $p";
            sleep 1

        done
    fi
    unset x

}

function rkflash_write_param() {

    # flash parameter
    if [[ -r "${FILE_PARAM}" ]]; then
        write_file "log" "*** rkflashtool: write file parameter named $1 "
        $(sudo ${rkflash} w 0x0 0x2 < "${FILE_PARAM}") && display_detected "${text_file_flashed}${FILE_PARAM}"
        sleep 1
    else
        display_error "${text_error_file_flashed}"
    fi

}

function rkflash_write_rom() {

    write_file "log" "*** rkflashtool: write rom to tablet "

    #for x in ${FILES[@]}; do
    for (( x=0 ; x < ${count["files"]} ; x++ )); do

        if [[ -r "${DIR_ROM}/${FILES[$x]}.img" ]]; then
            [[ "${FILES[$x]}" == "${FILES[4]}" ]] && x=8
            $(sudo ${rkflash} w ${mtd_offset[$x]} ${mtd_size[$x]} < ${DIR_ROM}/${mtd_name[$x]}.img)
            write_file "log" "${rkflash} w ${mtd_offset[$x]} ${mtd_size[$x]} < ${DIR_ROM}/${mtd_name[$x]}.img"
            display_mssg "n" "Flash ${mtd_name[$x]}"
            sleep 1
        fi

    done

    unset x

}

#function write_idb() {
    ##inspired by rksp tool?

#}

