#!/bin/bash

text_adb_reboot_bootloader="Le binaire ADB va redémarrer votre tablette dans le mode bootloader !\n Veuillez patienter ..."

text_config_file_exists="Le fichier config existe ... "

text_del_dir_afptool="Le répertoire créé par l'outil AFPTOOL a bien été supprimé !"
text_del_file_unpack="Le fichier créé par l'outil img_unpack a bien été supprimé !"

text_detect_tablet="Le programme va chercher à détecter votre tablette \n et vérifier que vous êtes dans le mode 'bootloader' !"

text_dir_ok="Ce répertoire a bien été créé : "

text_error_dir_afptool="Le répertoire de sauvegarde de l'outil AFPTOOL semble ne pas avoir été créé. \nVeuillez vérifier les messages de l'outil !"
text_error_file_flashed="Veuillez vérifier ! \n Il y a eu un problème durant le flash de ce fichier : "
text_error_flash="Erreur durant la phase de flash"
text_error_mode="Il semble que la tablette ne soit pas dans le mode bootloader nécessaire ...\n"
text_error_not_adb="L'outil ADB n'est pas installé. Veuillez faire le nécessaire !"
text_error_not_fastboot="L'outil Fastboot n'est pas installé. Veuillez faire le nécessaire !"
text_error_not_rkflashtool="L'outil rkflashtool n'existe pas dans le répertoire que vous avez indiqué. \nVeuillez indiquer un autre répertoire !"
text_error_not_rktools="Les outils rktools ne sont pas dans le répertoire que vous avez indiqué. \nVeuillez indiquer un autre répertoire !"
text_error_pid="Votre tablette n'a pas le bon identifiant produit : PID="

text_file_flashed="Ce fichier a bien été flashé : "

text_flash_rom="Veuillez patienter pendant que votre tablette soit flashée !"

text_goodbye="*** Au revoir ! ***"

text_ok_adb="L'outil ADB est bien installé !"
text_ok_fastboot="L'outil Fastboot est bien installé !"
text_ok_rkflashtool="L'outil rkflashtool a bien été détecté !"
text_ok_rktools="Les outils rktools ont bien été détectés !"

text_reboot_bootloader="Voulez-vous que le programme redémarre la tablette dans le mode bootloader ?\nSi vous cliquez sur le bouton [Non], cela signifie que vous devrez le faire manuellement."
text_reboot_bootloader_manu="Vous devez rebooter manuellement votre tablette. \n Veuillez le faire maintenant ; une fois fait, cliquez sur le bouton [Valider]!\nPuis patientez quelques secondes, que la tablette soit reconnue ... "

text_quit="(q: Quitter)"

text_save_tablet="Votre tablette va être sauvegardée !"

text_tablet_detected="Votre tablette a été détectée comme RK"

text_treatment_afptool="L'outil afptool va extraire les fichiers de votre ROM update ..."
text_treatment_img_unpack="L'outil img_unpack va traiter votre ROM update ..."

text_verify_installed="Le programme va vérifier que vous ayez bien les différents outils !"

text_welcome="Quelle action, désirez-vous faire :"
